### ISSUE TITLE
Starting new hydroshare repositories for each App

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/SWATshare#1]
@dtarb and @aphelionz and @jphuong 
After meeting with Venkatesh Merwade today and reviewing Geohub/HydroShare development issues encountered when using SWATshare APP, Venkatesh and I agreed that the best way to move forward with communications on debugging Apps is to start a new repository where testers/users can work directly with developers. 

This is my first time making a repository, It is private.   How do I set it up so that I can invite any HydroShare developer?  How do I add Venkatesh or any new student so that I can assign them to issues in this repository?  

I think this approach will help as we debug and make each App usable and will work with Dan to set up a repository like this for each of this Apps.  For App developers that are not HS PIs, do we want to have a repository for each App inside the Hydroshare repository, or leave it up to them? For example, HS users could go to the App developers Github site to report HydroShare issues there?

Thanks for helping me organize Mark! It's great to have a Developer Outreach Coordinator - let me know your suggestions for the best way to move forward.

**Comment by ChristinaB** [comment]
Luk Kim <kim1634@purdue.edu> and lanzhao@purdue.edu are the new students that I would like to add

**Comment by dtarb** [comment]
@mjstealey has been in charge of setting up other repositories, so could help with this one.  It seems a bit weird that this one has no code yet.  Are you planning on adding code.

**Comment by mjstealey** [comment]
@ChristinaB 

- In general private repositories are not free beyond the first one in Github. There is a charge either per person or per repo when repositories are going to be maintained as private. (I don't recall the current Github pricing structure for this...)
- For management of a new repository we can:
  - Create a new group (i.e. SWATshare) and make you an administrator of that group
  - Attach the new SWATshare repository to that group, by extension you would now manage that repository
  - Invite members to SWATshare group with corresponding rights to their role for the SWATshare repository (read / write / admin)

**Comment by aphelionz** [comment]
Does it need to be private?

**Comment by ChristinaB** [comment]
The issue is for App Developers to have a place within the HydroShare umbrella to share code and for users to submit issues and discuss bugs with App developers.  

I can take the privacy question and the code question back to Venkatesh.  What I know is that he has two student developers who he wants to be plugged into the HydroShare github environment so that they can work on improving the App using the Issues functionality.  Would this also work with Groups?  

Is it a possible future that some Apps have Groups and some Apps have a repository?

**Comment by ChristinaB** [comment]
@vmmerwade  Do you need a repository that is private? Or can it be public?    Do you plan on posting SwatShare App code in this repository?  Would you prefer to use a Group in Github?  Thanks!! C

**Comment by vmmerwade** [comment]
Christina:

 

I am copying I Luk and Lan. I think they will have the correct answers to your questions.

 

Venkatesh

**Comment by ChristinaB** [comment]
@aphelionz 
What is the process for adding new people into a repository. It looks like @yirugi and @lanzh are now in the system - but I'm not sure if @lanzh  is the correct Lan...
THanks! I'll get started on adding SWATshare App issues.
C

**Comment by aphelionz** [comment]
Check out the repository settings under access control. Alternatively, you can make a SWATshare team and add everybody there, then give the team itself access to the repo
