### ISSUE TITLE
Username compatability causing "Token Failed" Error

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/SWATshare#2]
This is confusion in setting up the accounts at launch: Geohub account, SWATshare account, linking to hydroshare account.  We tried multiple ways to set up GeoHub accounts, but encounter “error message: Token failed” and the initial image loading does not occur. This occurs with the OpenWith function of the SWAT Model for Cedar Creek -SMA Study, selecting the first  SWATshare WebApp 

I have tried to do it where I first log in to GeoHub and navigate the site successfully.  Then I go back to HydroShare, and can see the map with the OpenWith function of the SWAT Model for Cedar Creek -SMA Study, selecting the first  SWATshare WebApp.  HOWEVER, when I do the next step of SWATshare (Explore), I get a Token File Read Failure.  I can see the blank form of the model parameters hovering over the map, but it has a transparent cover
![image](https://cloud.githubusercontent.com/assets/4108369/24984496/9591ffb0-1fa2-11e7-9736-06467a38fe21.png)

and the Logging in the HydroShare message keeps looping - and appears to not be successful at logging in. 

![image](https://cloud.githubusercontent.com/assets/4108369/24984524/c070cea0-1fa2-11e7-94f1-3ae9b5889f56.png)

I get these errors with each OpenWith  option listed except the SWATshare APP, but all I can do with that is see the Cedar data mapped.  I explored the tabs and ended up with another Token error in the upload tab.
![image](https://cloud.githubusercontent.com/assets/4108369/24984605/3ca8669a-1fa3-11e7-83ef-74d26058864c.png)

**Comment by yirugi** [comment]
@ChristinaB  Thank you for the detail description! I'll look into the problem, and let you know.

**Comment by ChristinaB** [comment]
Thanks!!  So you know, I do have a CAPS difference in my usersnames.

In MyGeoHub
Name: Christina Bandaragoda
Username: christinabandaragoda
email: cband@uw.edu

In HydroShare
Name: Christina Bandaragoda
Username: ChristinaBandaragoda
email: cband@uw.edu

So the only difference is the Caps on the username.  Is it supposed to be the same username for both accounts??    There is no way for users to edit username in MyGeoHub or HydroShare.

**Comment by yirugi** [comment]
No, it does not care username since the authentication use OAUTH. It only requires tokens for accessing resources.

**Comment by ChristinaB** [comment]
I understand it requires tokens, but in these steps for getting the data to load, either the failure occurs at step 2 or 3 because of how the username/password were provided.  The workflow that I used to generate a new username may not have been as expected.  

1.   User Requests Access with Username / Password
2.   Application validates credentials
3.   Application provides a signed token to the client
4.   Client stores that token and sends it along with every request
5.   Server verifies token and responds with data

**Comment by yirugi** [comment]
@ChristinaB I found the reason of this problem. We recently changed communication format between SWATShare web client and web service server, and there was a mistake about handling error status. I just fixed it, and will deploy the code to MyGeoHub, but this takes time, few days, since we have code reviewing process.
